# Generated by Django 4.2.11 on 2024-04-28 01:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images')),
                ('post_type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('intitulé', models.TextField()),
                ('description', models.TextField()),
                ('lieu', models.TextField()),
                ('contactInfo', models.TextField()),
            ],
            bases=('posts.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('localisation', models.TextField()),
                ('description', models.TextField()),
                ('contactInfo', models.TextField()),
            ],
            bases=('posts.poste',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('recom', models.TextField()),
            ],
            bases=('posts.poste',),
        ),
        migrations.CreateModel(
            name='stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.poste')),
                ('typeStage', models.IntegerField(choices=[(0, 'ouvrier'), (1, 'technicien'), (1, 'PFE')])),
                ('societe', models.TextField()),
                ('duree', models.IntegerField()),
                ('sujet', models.TextField()),
                ('contactInfo', models.TextField()),
                ('specialité', models.TextField()),
            ],
            bases=('posts.poste',),
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.evenement')),
                ('club', models.TextField()),
            ],
            bases=('posts.evenement',),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.evenement')),
                ('prix', models.FloatField(verbose_name='')),
            ],
            bases=('posts.evenement',),
        ),
    ]
