# Generated by Django 4.2.11 on 2024-04-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_poste_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
