# Generated by Django 4.2.11 on 2024-04-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_poste_image_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='author',
        ),
    ]
