# Generated by Django 4.2.11 on 2024-04-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_poste_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='author',
        ),
    ]
