# Generated by Django 4.2.11 on 2024-05-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_poste_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
